config/routes.rb
Sandbox1::Application.routes.draw do

  get "static_pages/hospital"

  get "static_pages/help"

  get "doctors/search"
  get "doctors/department"
  resources :doctors

  resources :patients

  get "patients/new"

  match '/help',     to: 'static_pages#help'
  match '/hospital', to: 'static_pages#hospital'

  root to: 'static_pages#hospital'

end

app/models/doctor.rb
class Doctor < ActiveRecord::Base
  has_many :patients
  def full_name
    "#{first_name} #{last_name}"
  end
end

app/models/patient.rb
class Patient < ActiveRecord::Base
  belongs_to :doctor
  minsize_last_name=6
  validates :last_name, :presence => true,
            :length => {:minimum => minsize_last_name}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController
  # GET /doctors/department
  def department
    flash[:selected_dept] = params[:dept]
    @doctors = Doctor.where("department=?",params[:dept])
    flash[:doctors]=@doctors
    puts "...format="+request.format

    respond_to do |format|
      format.html {redirect_to(hospital_url)}
      format.js 
    end
  end

  # GET /doctors/search
  def search
    @doctors = Doctor.where("last_name like :str or first_name like :str",:str => '%'+params[:q]+'%')
    flash[:doctors]=@doctors
    puts "...format="+request.format

    respond_to do |format|
      format.html {redirect_to(hospital_url)}
      #format.js {render :js => "alert('I am in search js format')"}
      format.js 
    end

  end

  # GET /doctors
  # GET /doctors.json
  def index
    @doctors = Doctor.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @doctors }
    end
  end

  # GET /doctors/1
  # GET /doctors/1.json
  def show
    @doctor = Doctor.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @doctor }
    end
  end

  # GET /doctors/new
  # GET /doctors/new.json
  def new
    @doctor = Doctor.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @doctor }
    end
  end

  # GET /doctors/1/edit
  def edit
    @doctor = Doctor.find(params[:id])
  end

  # POST /doctors
  # POST /doctors.json
  def create
    @doctor = Doctor.new(params[:doctor])

    respond_to do |format|
      if @doctor.save
       format.html { redirect_to @doctor, notice: 'Doctor was successfully created.' }
       format.json { render json: @doctor, status: :created, location: @doctor }
      else
        format.html { render action: "new" }
        format.json { render json: @doctor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /doctors/1
  # PUT /doctors/1.json
  def update
    @doctor = Doctor.find(params[:id])

    respond_to do |format|
      if @doctor.update_attributes(params[:doctor])
        format.html { redirect_to @doctor, notice: 'Doctor was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @doctor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /doctors/1
  # DELETE /doctors/1.json
  def destroy
    @doctor = Doctor.find(params[:id])
    @doctor.destroy

    respond_to do |format|
      format.html { redirect_to doctors_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  # GET /patients
  # GET /patients.json
  def index
    @patients = Patient.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @patients }
    end
  end

  # GET /patients/1
  # GET /patients/1.json
  def show
    @patient = Patient.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @patient }
    end
  end

  # GET /patients/new
  # GET /patients/new.json
  def new
    @patient = Patient.new
    @minsize_last_name = 5;

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @patient }
    end
  end

  # GET /patients/1/edit
  def edit
    @patient = Patient.find(params[:id])
  end

  # POST /patients
  # POST /patients.json
  def create
    #SCAFFOLD: @patient = Patient.new(params[:patient])
    # Associate the patient with the doctor chosen
    @doctor = Doctor.find(params[:patient][:doctor_id])
    @patient = @doctor.patients.create(params[:patient])

    respond_to do |format|
      if @patient.save
        format.html { redirect_to @patient, notice: 'Patient was successfully created.' }
        format.json { render json: @patient, status: :created, location: @patient }
      else
        format.html { render action: "new" }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /patients/1
  # PUT /patients/1.json
  def update
    @patient = Patient.find(params[:id])

    respond_to do |format|
      if @patient.update_attributes(params[:patient])
        format.html { redirect_to @patient, notice: 'Patient was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /patients/1
  # DELETE /patients/1.json
  def destroy
    @patient = Patient.find(params[:id])
    @patient.destroy

    respond_to do |format|
      format.html { redirect_to patients_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def hospital
    @depts = Doctor.uniq.pluck(:department)

    # we take care not to try to get stuff if dept is nil
    #if (flash[:selected_dept]==nil) then 
      # flash[:selected_dept]=@depts[0] 
      # @doctors=Doctor.where("department=?",@depts[0])
      # flash[:doctors]=@doctors
    #end
  end

  def help
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/doctors/_description.html.erb
<!-- Print the descriptin for the selected doc -->
<h3>Description</h3>

<% if flash[:seldoc] %>
    <%= flash[:seldoc].description %>
<% end %>

<br />

app/views/doctors/_form.html.erb
<%= form_for(@doctor) do |f| %>
  <% if @doctor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@doctor.errors.count, "error") %> prohibited this doctor from being saved:</h2>

      <ul>
      <% @doctor.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br />
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :hospital %><br />
    <%= f.text_field :hospital %>
  </div>
  <div class="field">
    <%= f.label :department %><br />
    <%= f.text_field :department %>
  </div>
  <div class="field">
    <%= f.label :details %><br />
    <%= f.text_area :description, :cols => 100, :rows => 5 %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/doctors/_list.html.erb
<table>
  <tr>
    <th>First name</th>
    <th>Last name</th>
    <th>Department</th>
    <th>Hospital</th>
    <th>Description</th>
  </tr>

<% @doctors.each do |doctor| %>
  <tr>
    <td><%= doctor.first_name %></td>
    <td><%= doctor.last_name %></td>
    <td><%= doctor.department %></td>
    <td><%= doctor.hospital %></td>
    <td><%= doctor.description %></td>
  </tr>
<% end %>
</table>

<br />

app/views/doctors/_listnames.html.erb
<!-- List just the doctor names -->
<div id="doctors"> 
<h3>Doctors</h3>
<% if docs %>
  <% docs.each do |doctor| %>
    <li><%= doctor.full_name %></li>
    <% flash[:seldoc]=doctor %>
  <% end %>
<% end %>
</div>

app/views/doctors/department.html.erb
<h1>Doctors in department: <em><%= @selected_department %></em> </h1>
<table>
  <tr>
    <th>First name</th>
    <th>Last name</th>
    <th>Hospital</th>
    <th>Description</th>
  </tr>

<% @doctors.each do |doctor| %>
  <tr>
    <td><%= doctor.first_name %></td>
    <td><%= doctor.last_name %></td>
    <td><%= doctor.hospital %></td>
    <td><%= doctor.description %></td>
  </tr>
<% end %>
</table>

<br />
<%= link_to 'Back', hospital_path %>

app/views/doctors/department.js.erb
try{
  $("<%= escape_javascript(render :partial => '/doctors/listnames',
           :locals => {:docs=>flash[:doctors]}) %>").replaceAll('#doctors');
}
catch(e){
 alert('An error has occurred: '+e.message)
}
	     
// alert("done?");

app/views/doctors/edit.html.erb
<h1>Editing doctor</h1>

<%= render 'form' %>

<%= link_to 'Show', @doctor %> |
<%= link_to 'Back', doctors_path %>

app/views/doctors/index.html.erb
<h1>Listing doctors</h1>

<table>
  <tr>
    <th>First name</th>
    <th>Last name</th>
    <th>Department</th>
    <th>Hospital</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @doctors.each do |doctor| %>
  <tr>
    <td><%= doctor.first_name %></td>
    <td><%= doctor.last_name %></td>
    <td><%= doctor.department %></td>
    <td><%= doctor.hospital %></td>
    <td><%= link_to 'Show', doctor %></td>
    <td><%= link_to 'Edit', edit_doctor_path(doctor) %></td>
    <td><%= link_to 'Destroy', doctor, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Doctor', new_doctor_path %>

app/views/doctors/new.html.erb
<h1>New doctor</h1>

<%= render 'form' %>

<%= link_to 'Back', doctors_path %>

app/views/doctors/search.html.erb
<h1>Doctors matching the search</h1>

<%= render 'doctors/list' %>

<%= link_to 'Back', hospital_path %>

app/views/doctors/search.js.erb
try{
  $("<%= escape_javascript(render :partial => '/doctors/listnames',
           :locals => {:docs=>flash[:doctors]}) %>").replaceAll('#doctors');
}
catch(e){
 alert('An error has occurred: '+e.message)
}
	     
// alert("done?");

app/views/doctors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>First name:</b>
  <%= @doctor.first_name %>
</p>

<p>
  <b>Last name:</b>
  <%= @doctor.last_name %>
</p>
<p>
  <b>Department:</b>
  <%= @doctor.department %>
</p>
<p>
  <b>Description and Appointment times:</b>
  <%= @doctor.description %>
</p>
<p>
  <b>Primary Hospital:</b>
  <%= @doctor.hospital %>
</p>


<%= link_to 'Edit', edit_doctor_path(@doctor) %> |
<%= link_to 'Back', doctors_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Hospital</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tags %>
</head>
<body id="hospital">

   <div id="main">
     <%= yield %>
   </div>

</body>
</html>

app/views/patients/_form.html.erb
<%= form_for(@patient) do |f| %>
  <% if @patient.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@patient.errors.count, "error") %> prohibited this patient from being saved:</h2>

      <ul>
      <% @patient.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br />
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :date_of_birth %><br />
    <%= f.date_select :date_of_birth, {:use_short_month=>true,
                                       :start_year=>1900,
				       :end_year=>Time.now.year,
				       :default=>{:year=>Time.now.year - 40,
				                  :month=> 'Jun',
						  :day=>15}
				      }, 
				      {} %>
  </div>
  <div class="field">
    <%= f.label :patient_type %><br />
    <%= f.select :patient_type, options_for_select({'Out Patient'=> :outpatient,
                                                   'In patient'=> :inpatient},:outpatient)
			   %>
  </div>
  <div class="field">
    <%= f.label 'Doctor Name' %><br />
    <%= f.collection_select :doctor_id, Doctor.all, :id, :full_name, :prompt => true %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/patients/edit.html.erb
<h1>Editing patient</h1>

<%= render 'form' %>

<%= link_to 'Show', @patient %> |
<%= link_to 'Back', patients_path %>

app/views/patients/index.html.erb
<h1>Listing patients</h1>

<table>
  <tr>
    <th>First name</th>
    <th>Last name</th>
    <th>Date of birth</th>
    <th>Patient type</th>
    <th>Primary doctor</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @patients.each do |patient| %>
  <tr>
    <td><%= patient.first_name %></td>
    <td><%= patient.last_name %></td>
    <td><%= patient.date_of_birth %></td>
    <td><%= patient.patient_type %></td>
    <td><%= Doctor.find(patient.doctor_id).full_name %></td>
    <td><%= link_to 'Show', patient %></td>
    <td><%= link_to 'Edit', edit_patient_path(patient) %></td>
    <td><%= link_to 'Destroy', patient, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Patient', new_patient_path %>

app/views/patients/new.html.erb
<h1>New patient</h1>

<%= render 'form' %>

<%= link_to 'Back', patients_path %>

app/views/patients/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>First name:</b>
  <%= @patient.first_name %>
</p>

<p>
  <b>Last name:</b>
  <%= @patient.last_name %>
</p>

<p>
  <b>Date of birth:</b>
  <%= @patient.date_of_birth %>
</p>

<p>
  <b>Patient type:</b>
  <%= @patient.patient_type %>
</p>

<p>
  <b>Primary doctor:</b>
  <%= @patient.doctor_id %>
</p>


<%= link_to 'Edit', edit_patient_path(@patient) %> |
<%= link_to 'Back', patients_path %>

app/views/static_pages/help.html.erb
<h1>StaticPages#help</h1>
<p>Find me in app/views/static_pages/help.html.erb</p>

app/views/static_pages/hospital.html.erb
<h1>Hospital Cure All</h1>

<br>

<table align="left">
 <tr>
  <td>

   <h2>Select Department</h2>
   <%= form_tag('/doctors/department', :method=>:get, :remote=>true) do %>
   <% @depts.each do |dept| %>
    <%= radio_button_tag 'dept', dept, flash[:selected_dept]==dept %>
                          <!--      :onclick => "this.parentNode.submit()"  -->
    <%= label_tag "dept_#{dept}", dept.humanize %>
    <br>
    <% end %>
    <%= submit_tag("Update") %>
   <% end %>

   <br>
   <!-- search box for doctor/hospital etc.. in doctor model -->
   <h2>Search </h2>
    <%= form_tag('doctors/search', :method=>:get, :remote=>true) do %>
    <%= label_tag(:q, "Search for:") %>
    <%= text_field_tag(:q) %>
    <%= submit_tag("Search") %>
   <% end %>

  </td>

  <td>

   <div id="doctors">
    <%= render :partial=>'doctors/listnames',
               :locals=>{:docs=>flash[:doctors]} %>
   </div>

  </td>

  <td>
   <div id="doc_description">
    <%= render :partial=>'doctors/description',
               :locals=>{:seldoc=>flash[:seldoc]} %>
   </div>
  </td>

 </tr>
</table>


<br>

<div id="footer">
<a href="http://localhost:3000/rails_help.html">Rails Help</li>
</div>